name: jsr

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup Environment
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 2.x.x

      - name: Log versions
        run: |
          deno --version
      - name: Publish to JSR
        run: |
          deno publish
